### ISSUE TITLE
omega.generate_conformers fails for certain combinations of MMFF atom types; probably should default to 'loose' checking

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/gaff2xml#97]
There are many cases in which Omega will fail to generate conformations (after version 2.4.0) for small molecules due to missing MMFF parameters - basically it is "strict" about MMFF atom typing by default (since that version) and if an atom type is not present in MMFF it will fail to generate a conformation with a warning. Currently this is for some reason NOT caught by the exception handling in omega.generate_conformers.

An example such molecule (there are many more, but here's the one I have on hand) is:
B(c1cc[nH]n1)(O)O

Code snippet:
`
>>> mol2 = OEMol()
>>> OEParseSmiles(mol2, 'B(c1cc[nH]n1)(O)O')
True
>>> gaff2xml.openeye.generate_conformers(mol2)
Warning: no MMFF bend parameters for atoms 1 2 6
Warning: force field setup failed due to missing parameters for molecule`

My fix is twofold (half of which I have right now):
1) Add an optional argument to generate_conformers which turns ON strict atom typing (as discussed here - search for "SetStrictAtomTypes": https://docs.eyesopen.com/toolkits/python/omegatk/OEConfGenClasses/OEOmega.html) so that the nearest MMFF atom type will be used in these cases. In my view the default strictness level should be False (not strict) for our purposes. Otherwise, conformer generation will fail on essentially any large general database of compounds, as there are far too many cases not perfectly covered by MMFF.  

2) Fix the issue with exception handling. (Also, check whether the same issue of exception handling applies to the charge calculation function).

I can easily submit a pull request which will do the first of these, but I have to troubleshoot the second still.

**Comment by davidlmobley** [comment]
OK, with respect to the second of these - I'm an idiot. Apparently I was using the version of gaff2xml installed via conda, which is apparently NOT the same one whose code I was looking at. The conda version does not have exception handling in the code, hence the silent failure. The current github version is fine. 

So, only the first issue above is a 'real' issue. Though, maybe you need to set it so conda will pull down the more recent version?

I'll submit a pull request to fix the first issue above.

**Comment by davidlmobley** [comment]
#98 submitted.

**Comment by kyleabeauchamp** [comment]
Once we finish this pull request and the name change, I will roll out a new release and build some new conda packages.
